# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pyleniumio-playground

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Build project dependencies
      run: |
        python -m pip install --upgrade pip
        python3 --version
        pip install pipenv
        pipenv install --dev
        allure --version

    - name: Start selenoid
      uses: Xotabu4/selenoid-github-action@v1
    - uses: actions/checkout@v2

    - name: Test
      run: |
        ls -ll
        pipenv run pytest -n=4 tests --alluredir=./allure-results
      continue-on-error: true

    - name: Create Allure Report
      run: |
        ls -l
        allure generate -c ./allure-results -o ./allure-report
    - uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: ./allure-report