# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pyleniumio-playground

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 --version
        pip install pipenv
        pipenv install
        export VENV_HOME_DIR=$(pipenv --venv)
        source $VENV_HOME_DIR/bin/activate
        export PYTHONPATH="$PYTHONPATH:."
        python -c "import sys;print(sys.path)"
    - name: Build the stack
      run: docker-compose up -d
    - name: Sleep
      run: |
        sleep 20
    - name: Pytest
      run: |
        docker ps
        ls -ll
        python -m pytest --remote_url="http://localhost:4444/wd/hub"